// `.env.ts` is generated by the `npm run env` command
import env from './.env';
export const protectedResourceMap: [string, string[]][] = [
  ['https://graph.microsoft.com/v1.0/me', ['user.read']]
];
export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  config: {
    clientID: '08534e05-70a0-4f9f-ab9b-e42a144efd95',
    authority:
      'https://login.microsoftonline.com/e29e4c95-e51f-4486-853d-9eb06c8482d2/',
    validateAuthority: true,
    redirectUri: 'https://tds.eyindiaonetax.com/',
    postLogoutRedirectUri: 'https://tds.eyindiaonetax.com/',
    navigateToLoginRequestUrl: true,
    cacheLocation: 'localStorage',
    consentScopes: [
      'user.read',
      'openid',
      'profile',
      'api://a88bb933-319c-41b5-9f04-eff36d985612/access_as_user'
    ],
    unprotectedResources: ['https://www.microsoft.com/en-us/'],
    protectedResourceMap
  },
  LOGIN_RESOURCE_URL: 'https://login.microsoftonline.com',
  api: {
    authorization: '/api/authorization/',
    administration: '/api/administration/',
    challans: '/api/challans/',
    dashboards: '/api/dashboards/',
    masters: '/api/masters/',
    ingestion: '/api/ingestion/',
    onboarding: '/api/onboarding/',
    rateengine: '/api/rateengine/',
    returns: '/api/returns/',
    auth: '/api/auth/',
    admin: '/api/admin/',
    fvu: '/api/fvu-proxy/generate',
    validation: '/api/validation/',
    reports: '/api/reports/',
    zuulgatway: '/api/zuulgatway/',
    logger: '/api/ui-logger/log',
    panwebsocket: 'wss://tds.eyindiaonetax.com/ws',
    ldcwebsocket: 'wss://tds.eyindiaonetax.com/ws-ldc',
    singlepanwebsocket: 'wss://tds.eyindiaonetax.com/ws-singlepan',
    singleldcwebsocket: 'wss://tds.eyindiaonetax.com/ws-singleldc',
    filingwebsocket: 'wss://tds.eyindiaonetax.com/ws-filing',
    csiwebsocket: 'wss://tds.eyindiaonetax.com/csi',
    consolefilewebsocket: 'wss://tds.eyindiaonetax.com/consolesubmission',
    consoledownload: 'wss://tds.eyindiaonetax.com/consoledownload',
    consolesubmission: 'wss://tds.eyindiaonetax.com/consolesubmission',
    form16download: 'wss://tds.eyindiaonetax.com/form16download',
    utilizationwebsocket: 'wss://tds.eyindiaonetax.com/ws-utilization',
    form16submission: 'wss://tds.eyindiaonetax.com/form16submission',
    justificationdownload: 'wss://tds.eyindiaonetax.com/justificationdownload',
    justificationsubmission:
      'wss://tds.eyindiaonetax.com/justificationsubmission',
    residentsectionDetermination: '/api/flask/resident/section',
    nonResidentSectionDetermination: '/api/flask/non-resident/section',
    afterSectionDetermination: '/api/flask/invoice/tracking',
    flaskapi: 'api/flask',
    sparkapi: 'api/spark'
  },
  tenantConfigTypes: {
    databaseConfig: 'cosmos-config.',
    sftpConfig: 'sftp-config.',
    blobConfig: 'blob-storage.',
    powerbiConfig: 'power-bi.'
  },
  logger: {
    debug: {
      enabled: false
    },
    info: {
      enabled: false
    },
    warn: {
      enabled: true
    },
    error: {
      enabled: true
    }
  }
};
