//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.g;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SrlNo"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedInt"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IdenficationNum"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15G}nonEmptyString"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NatureOfInc"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15G}nonEmptyString"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DeductSection"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="192A"/&gt;
 *               &lt;enumeration value="193"/&gt;
 *               &lt;enumeration value="194"/&gt;
 *               &lt;enumeration value="194A"/&gt;
 *               &lt;enumeration value="194D"/&gt;
 *               &lt;enumeration value="194DA"/&gt;
 *               &lt;enumeration value="194EE"/&gt;
 *               &lt;enumeration value="194I"/&gt;
 *               &lt;enumeration value="194K"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AmtOfInc"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedLong"&gt;
 *               &lt;totalDigits value="14"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "srlNo",
    "idenficationNum",
    "natureOfInc",
    "deductSection",
    "amtOfInc"
})
@XmlRootElement(name = "IncomeDtl")
public class IncomeDtl {

    @XmlElement(name = "SrlNo")
    protected long srlNo;
    @XmlElement(name = "IdenficationNum", required = true)
    protected String idenficationNum;
    @XmlElement(name = "NatureOfInc", required = true)
    protected String natureOfInc;
    @XmlElement(name = "DeductSection", required = true)
    protected String deductSection;
    @XmlElement(name = "AmtOfInc", required = true)
    protected BigInteger amtOfInc;

    /**
     * Gets the value of the srlNo property.
     * 
     */
    public long getSrlNo() {
        return srlNo;
    }

    /**
     * Sets the value of the srlNo property.
     * 
     */
    public void setSrlNo(long value) {
        this.srlNo = value;
    }

    /**
     * Gets the value of the idenficationNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdenficationNum() {
        return idenficationNum;
    }

    /**
     * Sets the value of the idenficationNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdenficationNum(String value) {
        this.idenficationNum = value;
    }

    /**
     * Gets the value of the natureOfInc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNatureOfInc() {
        return natureOfInc;
    }

    /**
     * Sets the value of the natureOfInc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNatureOfInc(String value) {
        this.natureOfInc = value;
    }

    /**
     * Gets the value of the deductSection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeductSection() {
        return deductSection;
    }

    /**
     * Sets the value of the deductSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeductSection(String value) {
        this.deductSection = value;
    }

    /**
     * Gets the value of the amtOfInc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAmtOfInc() {
        return amtOfInc;
    }

    /**
     * Sets the value of the amtOfInc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAmtOfInc(BigInteger value) {
        this.amtOfInc = value;
    }

}
