UPDATE tds.state SET name = 'TELANGANA' WHERE name='Telangana';
UPDATE tds.state SET name = 'ANDHRA PRADESH' WHERE name='Andhra Pradesh';
UPDATE tds.state SET name = 'TAMILNADU' WHERE name='Tamil Nadu';

insert into tds.state (name, country_id) select 'ANDAMAN AND NICOBAR ISLANDS', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'ANDAMAN AND NICOBAR ISLANDS');
insert into tds.state (name,country_id) select 'ANDHRA PRADESH', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'ANDHRA PRADESH');
insert into tds.state (name,country_id) select 'ARUNACHAL PRADESH', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'ARUNACHAL PRADESH');
insert into tds.state (name,country_id) select 'ASSAM', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'ASSAM');
insert into tds.state (name,country_id) select 'BIHAR', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'BIHAR');
insert into tds.state (name,country_id) select 'CHANDIGARH', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'CHANDIGARH');
insert into tds.state (name,country_id) select 'DADRA and NAGAR HAVELI', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'DADRA and NAGAR HAVELI');
insert into tds.state (name,country_id) select 'DAMAN and DIU', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'DAMAN and DIU');
insert into tds.state (name,country_id) select 'DELHI' , (select id from tds.country where name='India')where not exists (select 1 from tds.state where name= 'DELHI');
insert into tds.state (name,country_id) select 'GOA', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'GOA');
insert into tds.state (name,country_id) select 'GUJARAT', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'GUJARAT');
insert into tds.state (name,country_id) select 'HARYANA', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'HARYANA');
insert into tds.state (name,country_id) select 'HIMACHAL PRADESH', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'HIMACHAL PRADESH');
insert into tds.state (name,country_id) select 'JAMMU and KASHMIR', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'JAMMU and KASHMIR');
insert into tds.state (name,country_id) select 'KARNATAKA' , (select id from tds.country where name='India')where not exists (select 1 from tds.state where name= 'KARNATAKA');
insert into tds.state (name,country_id) select 'KERALA', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'KERALA');
insert into tds.state (name,country_id) select 'LAKSHWADEEP', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'LAKSHWADEEP');
insert into tds.state (name,country_id) select 'MADHYA PRADESH', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'MADHYA PRADESH');
insert into tds.state (name,country_id) select 'MAHARASHTRA', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'MAHARASHTRA');
insert into tds.state (name,country_id) select 'MANIPUR', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'MANIPUR');
insert into tds.state (name,country_id) select 'MEGHALAYA', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'MEGHALAYA');
insert into tds.state (name,country_id) select 'MIZORAM', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'MIZORAM');
insert into tds.state (name,country_id) select 'NAGALAND', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'NAGALAND');
insert into tds.state (name,country_id) select 'ODISHA', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'ODISHA');
insert into tds.state (name,country_id) select 'PONDICHERRY', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'PONDICHERRY');
insert into tds.state (name,country_id) select 'PUNJAB' , (select id from tds.country where name='India')where not exists (select 1 from tds.state where name= 'PUNJAB');
insert into tds.state (name,country_id) select 'RAJASTHAN' , (select id from tds.country where name='India')where not exists (select 1 from tds.state where name= 'RAJASTHAN');
insert into tds.state (name,country_id) select 'SIKKIM' , (select id from tds.country where name='India')where not exists (select 1 from tds.state where name= 'SIKKIM');
insert into tds.state (name,country_id) select 'TAMILNADU', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'TAMILNADU');
insert into tds.state (name,country_id) select 'TRIPURA', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'TRIPURA');
insert into tds.state (name,country_id) select 'UTTAR PRADESH', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'UTTAR PRADESH');
insert into tds.state (name,country_id) select 'WEST BENGAL', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'WEST BENGALISLANDS');
insert into tds.state (name,country_id) select 'CHHATISHGARH', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'CHHATISHGARH');
insert into tds.state (name,country_id) select 'UTTARAKHAND', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'UTTARAKHAND');
insert into tds.state (name,country_id) select 'JHARKHAND', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'JHARKHAND');
insert into tds.state (name,country_id) select 'TELANGANA', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'TELANGANA');
insert into tds.state (name,country_id) select 'OTHERS', (select id from tds.country where name='India') where not exists (select 1 from tds.state where name= 'OTHERS');
