update tds.[country] set currency = 'Indian Rupee', symbol='INR' 
	where id=(select id from tds.[country] where name='India');

update tds.[country] set currency = 'Pakistan Rupee', symbol='PKR'
	where id=(select Id from tds.[country] where name='Pakistan');

insert into tds.country(name,active,created_by,modified_by,created_date,modified_date,currency,symbol)
values
    ('American Samoa',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'US Dollar','USD'),
    ('Germany',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Greece',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Guadeloupe',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Holy See (Vatican City State)',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Ireland',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Italy',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Latvia',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Luxembourg',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Malta',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Martinique',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Mayotte',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Monaco',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Montenegro',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Netherlands',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Portugal',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Réunion',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Saint Barthélemy',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Saint Martin (French part)',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Saint Pierre and Miquelon',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('San Marino',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Slovakia',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Slovenia',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Spain',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Euro','EUR'),
    ('Guernsey',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Pound Sterling','GBP'),
    ('Isle of Man',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Pound Sterling','GBP'),
    ('Jersey',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Pound Sterling','GBP'),
    ('United Kingdom',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Pound Sterling','GBP'),
    ('Japan',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Yen','JPY'),
    ('Switzerland',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Swiss Franc','CHF'),
    ('Liechtenstein',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Swiss Franc','CHF'),
    ('Australia',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Australian Dollar','AUD'),
    ('Christmas Island',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Australian Dollar','AUD'),
    ('Cocos (Keeling) Islands',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Australian Dollar','AUD'),
    ('Heard Island and McDonald Islands',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Australian Dollar','AUD'),
    ('Kiribati',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Australian Dollar','AUD'),
    ('Nauru',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Australian Dollar','AUD'),
    ('Norfolk Island',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Australian Dollar','AUD'),
    ('Tuvalu',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Australian Dollar','AUD'),
    ('Cook Islands',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'New Zealand Dollar','NZD'),
    ('New Zealand',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'New Zealand Dollar','NZD'),
    ('Niue',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'New Zealand Dollar','NZD'),
    ('Pitcairn',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'New Zealand Dollar','NZD'),
    ('Tokelau',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'New Zealand Dollar','NZD'),
    ('Singapore',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Singapore Dollar','SGD'),
    ('Canada',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Canadian Dollar','CAD'),
    ('Hong Kong',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Hong Kong Dollar','HKD'),
    ('Denmark',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Danish Krone','DKK'),
    ('Faroe Islands',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Danish Krone','DKK'),
    ('Greenland',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Danish Krone','DKK'),
    ('Bouvet Island',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Norwegian Krone','NOK'),
    ('Norway',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Norwegian Krone','NOK'),
    ('Svalbard and Jan Mayen',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Norwegian Krone','NOK'),
    ('Sweden',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Swedish Krona','SEK'),
    ('Bahrain',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Bahraini Dinar','BHD'),
    ('Kuwait',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Kuwaiti Dinar','KWD'),
    ('United Arab Emirates',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'UAE Dirham','AED'),
    ('Saudi Arabia',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Saudi Riyal','SAR'),
    ('South Africa',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Rand','ZAR'),
    ('China',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Yuan Renminbi','CNY'),
    ('Oman',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Rial Omani','OMR'),
    ('Qatar',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Qatari Rial','QAR'),
    ('Turkey',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'New Turkish Lira','TRY'),
    ('Korea, Republic of',1,'EY Admin','EY Admin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'Won','KRW');
