insert into tds.filing_state_code (state_name,state_code) VALUES ('ANDAMAN AND NICOBAR ISLANDS','1'), ('ANDHRA PRADESH','2'), ('ARUNACHAL PRADESH','3'), ('ASSAM','4'), ('BIHAR','5'), ('CHANDIGARH','6'), ('DADRA AND NAGAR HAVELI','7'), ('DAMAN AND DIU','8'), ('DELHI','9'), ('GOA','10'), ('GUJARAT','11'), ('HARYANA','12'), ('HIMACHAL PRADESH','13'), ('JAMMU and KASHMIR','14'), ('KARNATAKA','15'), ('KERALA','16'), ('LAKSHWADEEP','17'), ('MADHYA PRADESH','18'), ('MAHARASHTRA','19'), ('MANIPUR','20'), ('MEGHALAYA','21'), ('MIZORAM','22'), ('NAGALAND','23'), ('ODISHA','24'), ('PONDICHERRY','25'), ('PUNJAB','26'), ('RAJASTHAN','27'), ('SIKKIM','28'), ('TAMILNADU','29'), ('TRIPURA','30'), ('UTTAR PRADESH','31'), ('WEST BENGAL','32'), ('CHHATISHGARH','33'), ('UTTARAKHAND','34'), ('JHARKHAND','35'), ('TELANGANA','36'), ('LADAKH','37'), ('OTHERS','99');

insert into tds.filing_section_code (section_name, section_code) VALUES ('193', '193'), ('194', '194'), ('194A', '94A'), ('194B', '94B'), ('194BB', '4BB'), ('194C', '94C'), ('194D', '94D'), ('194EE', '4EE'), ('194F', '94F'), ('194G', '94G'), ('194H', '94H'), ('194I', '94I'), ('194I', '4IA'), ('194I', '4IB'), ('194J', '94J'), ('194LA', '94L'), ('194LBA', '4BA'), ('194DA', '4DA'), ('192A', '2AA'), ('194LBB', 'LBB'), ('194IA', '9IA'), ('194LBC', 'LBC'), ('194IC', '4IC');

insert into tds.filing_ministry_code (ministry_name, ministry_code) VALUES ('Agriculture', '01'), ('Atomic Energy', '02'), ('Fertilizers', '03'), ('Chemicals and Petrochemicals', '04'), ('Civil Aviation and Tourism', '05'), ('Coal', '06'), ('Consumer Affairs Food and Public Distribution', '07'), ('Commerce and Textiles', '08'), ('Environment and Forests and Ministry of Earth Science', '09'), ('External Affairs and Overseas Indian Affairs', '10'), ('Finance', '11'), ('Central Board of Direct Taxes', '12'), ('Central Board of Excise and Customs', '13'), ('Contoller of Aid Accounts and Audit', '14'), ('Central Pension Accounting Office', '15'), ('Food Processing Industries', '16'), ('Health and Family Welfare', '17'), ('Home Affairs and Development of North Eastern Region', '18'), ('Human Resource Development', '19'), ('Industry', '20'), ('Information and Broadcasting', '21'), ('Telecommunication and Information Technology', '22'), ('Labour', '23'), ('Law and Justice and Company Affairs', '24'), ('Personnel Public Grievances and Pesions', '25'), ('Petroleum and Natural Gas', '26'), ('Plannning Statistics and Programme Implementation', '27'), ('Power', '28'), ('New and Renewable Energy', '29'), ('Rural Development and Panchayati Raj', '30'), ('Science And Technology', '31'), ('Space', '32'), ('Steel', '33'), ('Mines', '34'), ('Social Justice and Empowerment', '35'), ('Tribal Affairs', '36'), ('D/o Commerce (Supply Division)', '37'), ('Shipping and Road Transport and Highways', '38'), ('Urban Development, Urban Employment and Poverty Alleviation', '39'), ('Water Resources', '40'), ('President Secretariat', '41'), ('Lok Sabha Secretariat', '42'), ('Rajya Sabha secretariat', '43'), ('Election Commission', '44'), ('Ministry of Defence (Controller General of Defence Accounts)', '45'), ('Ministry of Railways', '46'), ('Department of Posts', '47'), ('Department of Telecommunications', '48'), ('Andaman and Nicobar Islands Administration', '49'), ('Chandigarh Administration', '50'), ('Dadra and Nagar Haveli', '51'), ('Goa Daman and Diu', '52'), ('Lakshadweep', '53'), ('Pondicherry Administration', '54'), ('Pay and Accounts Officers (Audit)', '55'), ('Ministry of Non-conventional energy sources', '56'), ('Government Of NCT of Delhi', '57'), ('Others', '99');

insert into tds.filing_deductor_collector (category_description,category_value) VALUES ('Central Government','A'), ('State Government','S'), ('Statutory body (Central Govt)','D'), ('Statutory body (State Govt)','E'), ('Autonomous body (Central Govt)','G'), ('Autonomous body (State Govt)','H'), ('Local Authority (Central Govt)','L'), ('Local Authority (State Govt)','N'), ('Company','K'), ('Branch / Division of Company','M'), ('Association of Person (AOP)','P'), ('Association of Person (Trust)','T'), ('Artificial Juridical Person','J'), ('Body of Individuals','B'), ('Individual/HUF','Q'), ('Firm','F');

insert into tds.filing_minor_head_code ( particulars, code ) VALUES ( 'TDS payable by taxpayer', '200' ), ( 'TDS regular assessment (Raised by I.T, Dept.)', '400' );
