ALTER TABLE tds.activity_tracker DROP COLUMN IF EXISTS is_duedate_for_activity;
ALTER TABLE tds.activity_tracker DROP COLUMN IF EXISTS activity_type;
ALTER TABLE tds.activity_tracker DROP COLUMN IF EXISTS duedate_for_activity;
insert into tds.activity(activity_name,activity_group) select 'PAN Verification','Validation' where not exists (select 1 from tds.activity where activity_name= 'PAN Verification');
insert into tds.activity(activity_name,activity_group) select 'LDC Verification','Validation' where not exists (select 1 from tds.activity where activity_name= 'LDC Verification');
insert into tds.activity(activity_name,activity_group) select 'PDF Transaction','Transaction' where not exists (select 1 from tds.activity where activity_name= 'PDF Transaction');
insert into tds.activity(activity_name,activity_group) select 'TDS Calculation','Transaction' where not exists (select 1 from tds.activity where activity_name= 'TDS Calculation');
insert into tds.activity(activity_name,activity_group) select 'Monthly-Challan Generated','Challans' where not exists (select 1 from tds.activity where activity_name= 'Monthly-Challan Generated');
insert into tds.activity(activity_name,activity_group) select 'Monthly-Challan Receipt Uploaded','Challans' where not exists (select 1 from tds.activity where activity_name= 'Monthly-Challan Receipt Uploaded');
insert into tds.activity(activity_name,activity_group) select 'Quarterly TDS Filing','Filing' where not exists (select 1 from tds.activity where activity_name= 'Quarterly TDS Filing');
