//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.ca;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NameAcctnt" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}nameType" minOccurs="0"/&gt;
 *         &lt;element name="NameFirmAcctnt" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}nameType" minOccurs="0"/&gt;
 *         &lt;element name="AcctntAddrs" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}acntntAddressType" minOccurs="0"/&gt;
 *         &lt;element name="MembershipNumber" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{6}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CertDate" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CertNumber" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="15"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameAcctnt",
    "nameFirmAcctnt",
    "acctntAddrs",
    "membershipNumber",
    "certDate",
    "certNumber"
})
@XmlRootElement(name = "AcctntDetls")
public class AcctntDetls {

    @XmlElement(name = "NameAcctnt")
    protected String nameAcctnt;
    @XmlElement(name = "NameFirmAcctnt")
    protected String nameFirmAcctnt;
    @XmlElement(name = "AcctntAddrs")
    protected AcntntAddressType acctntAddrs;
    @XmlElement(name = "MembershipNumber")
    protected String membershipNumber;
    @XmlElement(name = "CertDate")
    protected XMLGregorianCalendar certDate;
    @XmlElement(name = "CertNumber")
    protected String certNumber;

    /**
     * Gets the value of the nameAcctnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameAcctnt() {
        return nameAcctnt;
    }

    /**
     * Sets the value of the nameAcctnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameAcctnt(String value) {
        this.nameAcctnt = value;
    }

    /**
     * Gets the value of the nameFirmAcctnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameFirmAcctnt() {
        return nameFirmAcctnt;
    }

    /**
     * Sets the value of the nameFirmAcctnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameFirmAcctnt(String value) {
        this.nameFirmAcctnt = value;
    }

    /**
     * Gets the value of the acctntAddrs property.
     * 
     * @return
     *     possible object is
     *     {@link AcntntAddressType }
     *     
     */
    public AcntntAddressType getAcctntAddrs() {
        return acctntAddrs;
    }

    /**
     * Sets the value of the acctntAddrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcntntAddressType }
     *     
     */
    public void setAcctntAddrs(AcntntAddressType value) {
        this.acctntAddrs = value;
    }

    /**
     * Gets the value of the membershipNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMembershipNumber() {
        return membershipNumber;
    }

    /**
     * Sets the value of the membershipNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMembershipNumber(String value) {
        this.membershipNumber = value;
    }

    /**
     * Gets the value of the certDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCertDate() {
        return certDate;
    }

    /**
     * Sets the value of the certDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCertDate(XMLGregorianCalendar value) {
        this.certDate = value;
    }

    /**
     * Gets the value of the certNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertNumber() {
        return certNumber;
    }

    /**
     * Sets the value of the certNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertNumber(String value) {
        this.certNumber = value;
    }

}
