//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.ca;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OrderAoFlg" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="Y|N"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CertSection" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="15"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NameAo" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DesgAo" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OrderDateAo" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OrderNumAo" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="10"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderAoFlg",
    "certSection",
    "nameAo",
    "desgAo",
    "orderDateAo",
    "orderNumAo"
})
@XmlRootElement(name = "AoOrderDetls")
public class AoOrderDetls {

    @XmlElement(name = "OrderAoFlg")
    protected String orderAoFlg;
    @XmlElement(name = "CertSection")
    protected String certSection;
    @XmlElement(name = "NameAo")
    protected String nameAo;
    @XmlElement(name = "DesgAo")
    protected String desgAo;
    @XmlElement(name = "OrderDateAo")
    protected XMLGregorianCalendar orderDateAo;
    @XmlElement(name = "OrderNumAo")
    protected String orderNumAo;

    /**
     * Gets the value of the orderAoFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderAoFlg() {
        return orderAoFlg;
    }

    /**
     * Sets the value of the orderAoFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderAoFlg(String value) {
        this.orderAoFlg = value;
    }

    /**
     * Gets the value of the certSection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertSection() {
        return certSection;
    }

    /**
     * Sets the value of the certSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertSection(String value) {
        this.certSection = value;
    }

    /**
     * Gets the value of the nameAo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameAo() {
        return nameAo;
    }

    /**
     * Sets the value of the nameAo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameAo(String value) {
        this.nameAo = value;
    }

    /**
     * Gets the value of the desgAo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesgAo() {
        return desgAo;
    }

    /**
     * Sets the value of the desgAo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesgAo(String value) {
        this.desgAo = value;
    }

    /**
     * Gets the value of the orderDateAo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrderDateAo() {
        return orderDateAo;
    }

    /**
     * Sets the value of the orderDateAo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderDateAo(XMLGregorianCalendar value) {
        this.orderDateAo = value;
    }

    /**
     * Gets the value of the orderNumAo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNumAo() {
        return orderNumAo;
    }

    /**
     * Sets the value of the orderNumAo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNumAo(String value) {
        this.orderNumAo = value;
    }

}
