//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.ca;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}SWVersionNo"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}SWCreatedBy"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}XMLCreatedBy"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}XMLCreationDate"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}IntermediaryCity"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "swVersionNo",
    "swCreatedBy",
    "xmlCreatedBy",
    "xmlCreationDate",
    "intermediaryCity"
})
@XmlRootElement(name = "CreationInfo", namespace = "http://incometaxindiaefiling.gov.in/common")
public class CreationInfo {

    @XmlElement(name = "SWVersionNo", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected String swVersionNo;
    @XmlElement(name = "SWCreatedBy", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected String swCreatedBy;
    @XmlElement(name = "XMLCreatedBy", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected String xmlCreatedBy;
    @XmlElement(name = "XMLCreationDate", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar xmlCreationDate;
    @XmlElement(name = "IntermediaryCity", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected String intermediaryCity;

    /**
     * Gets the value of the swVersionNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWVersionNo() {
        return swVersionNo;
    }

    /**
     * Sets the value of the swVersionNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWVersionNo(String value) {
        this.swVersionNo = value;
    }

    /**
     * Gets the value of the swCreatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWCreatedBy() {
        return swCreatedBy;
    }

    /**
     * Sets the value of the swCreatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWCreatedBy(String value) {
        this.swCreatedBy = value;
    }

    /**
     * Gets the value of the xmlCreatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXMLCreatedBy() {
        return xmlCreatedBy;
    }

    /**
     * Sets the value of the xmlCreatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXMLCreatedBy(String value) {
        this.xmlCreatedBy = value;
    }

    /**
     * Gets the value of the xmlCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getXMLCreationDate() {
        return xmlCreationDate;
    }

    /**
     * Sets the value of the xmlCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setXMLCreationDate(XMLGregorianCalendar value) {
        this.xmlCreationDate = value;
    }

    /**
     * Gets the value of the intermediaryCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermediaryCity() {
        return intermediaryCity;
    }

    /**
     * Sets the value of the intermediaryCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermediaryCity(String value) {
        this.intermediaryCity = value;
    }

}
