//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.ca;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}CreationInfo"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}Form_Details"/&gt;
 *         &lt;element name="PartType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="(PA)|(PB)|(PC)|(PD)"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/FORM15CAB}RemitterDetls"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/FORM15CAB}RemitteeDetls"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/FORM15CAB}RemittanceDetls"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/FORM15CAB}AcctntDetls" minOccurs="0"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/FORM15CAB}AoOrderDetls" minOccurs="0"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/FORM15CAB}ItActDetails" minOccurs="0"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/FORM15CAB}DTAADetails" minOccurs="0"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/FORM15CAB}TDSDetails" minOccurs="0"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/FORM15CAB}Declaration"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "creationInfo",
        "formDetails",
        "partType",
        "remitterDetls",
        "remitteeDetls",
        "remittanceDetls",
        "acctntDetls",
        "aoOrderDetls",
        "itActDetails",
        "dtaaDetails",
        "tdsDetails",
        "declaration"
})
@XmlRootElement(name = "FORM15CA")
public class FORM15CA {

    @XmlElement(name = "CreationInfo", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected CreationInfo creationInfo;
    @XmlElement(name = "Form_Details", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected FormDetails formDetails;
    @XmlElement(name = "PartType", required = true)
    protected String partType;
    @XmlElement(name = "RemitterDetls", required = true)
    protected RemitterDetls remitterDetls;
    @XmlElement(name = "RemitteeDetls", required = true)
    protected RemitteeDetls remitteeDetls;
    @XmlElement(name = "RemittanceDetls", required = true)
    protected RemittanceDetls remittanceDetls;
    @XmlElement(name = "AcctntDetls")
    protected AcctntDetls acctntDetls;
    @XmlElement(name = "AoOrderDetls")
    protected AoOrderDetls aoOrderDetls;
    @XmlElement(name = "ItActDetails")
    protected ItActDetails itActDetails;
    @XmlElement(name = "DTAADetails")
    protected DTAADetails dtaaDetails;
    @XmlElement(name = "TDSDetails")
    protected TDSDetails tdsDetails;
    @XmlElement(name = "Declaration", required = true)
    protected Declaration declaration;

    /**
     * Gets the value of the creationInfo property.
     *
     * @return possible object is
     * {@link CreationInfo }
     */
    public CreationInfo getCreationInfo() {
        return creationInfo;
    }

    /**
     * Sets the value of the creationInfo property.
     *
     * @param value allowed object is
     *              {@link CreationInfo }
     */
    public void setCreationInfo(CreationInfo value) {
        this.creationInfo = value;
    }

    /**
     * Gets the value of the formDetails property.
     *
     * @return possible object is
     * {@link FormDetails }
     */
    public FormDetails getFormDetails() {
        return formDetails;
    }

    /**
     * Sets the value of the formDetails property.
     *
     * @param value allowed object is
     *              {@link FormDetails }
     */
    public void setFormDetails(FormDetails value) {
        this.formDetails = value;
    }

    /**
     * Gets the value of the partType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPartType() {
        return partType;
    }

    /**
     * Sets the value of the partType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPartType(String value) {
        this.partType = value;
    }

    /**
     * Gets the value of the remitterDetls property.
     *
     * @return possible object is
     * {@link RemitterDetls }
     */
    public RemitterDetls getRemitterDetls() {
        return remitterDetls;
    }

    /**
     * Sets the value of the remitterDetls property.
     *
     * @param value allowed object is
     *              {@link RemitterDetls }
     */
    public void setRemitterDetls(RemitterDetls value) {
        this.remitterDetls = value;
    }

    /**
     * Gets the value of the remitteeDetls property.
     *
     * @return possible object is
     * {@link RemitteeDetls }
     */
    public RemitteeDetls getRemitteeDetls() {
        return remitteeDetls;
    }

    /**
     * Sets the value of the remitteeDetls property.
     *
     * @param value allowed object is
     *              {@link RemitteeDetls }
     */
    public void setRemitteeDetls(RemitteeDetls value) {
        this.remitteeDetls = value;
    }

    /**
     * Gets the value of the remittanceDetls property.
     *
     * @return possible object is
     * {@link RemittanceDetls }
     */
    public RemittanceDetls getRemittanceDetls() {
        return remittanceDetls;
    }

    /**
     * Sets the value of the remittanceDetls property.
     *
     * @param value allowed object is
     *              {@link RemittanceDetls }
     */
    public void setRemittanceDetls(RemittanceDetls value) {
        this.remittanceDetls = value;
    }

    /**
     * Gets the value of the acctntDetls property.
     *
     * @return possible object is
     * {@link AcctntDetls }
     */
    public AcctntDetls getAcctntDetls() {
        return acctntDetls;
    }

    /**
     * Sets the value of the acctntDetls property.
     *
     * @param value allowed object is
     *              {@link AcctntDetls }
     */
    public void setAcctntDetls(AcctntDetls value) {
        this.acctntDetls = value;
    }

    /**
     * Gets the value of the aoOrderDetls property.
     *
     * @return possible object is
     * {@link AoOrderDetls }
     */
    public AoOrderDetls getAoOrderDetls() {
        return aoOrderDetls;
    }

    /**
     * Sets the value of the aoOrderDetls property.
     *
     * @param value allowed object is
     *              {@link AoOrderDetls }
     */
    public void setAoOrderDetls(AoOrderDetls value) {
        this.aoOrderDetls = value;
    }

    /**
     * Gets the value of the itActDetails property.
     *
     * @return possible object is
     * {@link ItActDetails }
     */
    public ItActDetails getItActDetails() {
        return itActDetails;
    }

    /**
     * Sets the value of the itActDetails property.
     *
     * @param value allowed object is
     *              {@link ItActDetails }
     */
    public void setItActDetails(ItActDetails value) {
        this.itActDetails = value;
    }

    /**
     * Gets the value of the dtaaDetails property.
     *
     * @return possible object is
     * {@link DTAADetails }
     */
    public DTAADetails getDTAADetails() {
        return dtaaDetails;
    }

    /**
     * Sets the value of the dtaaDetails property.
     *
     * @param value allowed object is
     *              {@link DTAADetails }
     */
    public void setDTAADetails(DTAADetails value) {
        this.dtaaDetails = value;
    }

    /**
     * Gets the value of the tdsDetails property.
     *
     * @return possible object is
     * {@link TDSDetails }
     */
    public TDSDetails getTDSDetails() {
        return tdsDetails;
    }

    /**
     * Sets the value of the tdsDetails property.
     *
     * @param value allowed object is
     *              {@link TDSDetails }
     */
    public void setTDSDetails(TDSDetails value) {
        this.tdsDetails = value;
    }

    /**
     * Gets the value of the declaration property.
     *
     * @return possible object is
     * {@link Declaration }
     */
    public Declaration getDeclaration() {
        return declaration;
    }

    /**
     * Sets the value of the declaration property.
     *
     * @param value allowed object is
     *              {@link Declaration }
     */
    public void setDeclaration(Declaration value) {
        this.declaration = value;
    }

}
