//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.ca;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}FormName"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}Description"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}AssessmentYear"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}SchemaVer"/&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}FormVer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "formName",
    "description",
    "assessmentYear",
    "schemaVer",
    "formVer"
})
@XmlRootElement(name = "Form_Details", namespace = "http://incometaxindiaefiling.gov.in/common")
public class FormDetails {

    @XmlElement(name = "FormName", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected String formName;
    @XmlElement(name = "Description", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected String description;
    @XmlElement(name = "AssessmentYear", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected String assessmentYear;
    @XmlElement(name = "SchemaVer", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected String schemaVer;
    @XmlElement(name = "FormVer", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected BigDecimal formVer;

    /**
     * Gets the value of the formName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormName() {
        return formName;
    }

    /**
     * Sets the value of the formName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormName(String value) {
        this.formName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the assessmentYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessmentYear() {
        return assessmentYear;
    }

    /**
     * Sets the value of the assessmentYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessmentYear(String value) {
        this.assessmentYear = value;
    }

    /**
     * Gets the value of the schemaVer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVer() {
        return schemaVer;
    }

    /**
     * Sets the value of the schemaVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVer(String value) {
        this.schemaVer = value;
    }

    /**
     * Gets the value of the formVer property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFormVer() {
        return formVer;
    }

    /**
     * Sets the value of the formVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFormVer(BigDecimal value) {
        this.formVer = value;
    }

}
