//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.ca;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SecRemCovered" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="30"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AmtIncChrgIt" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}positiveDecimalAmt" minOccurs="0"/&gt;
 *         &lt;element name="TaxLiablIt" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}positiveDecimalAmt" minOccurs="0"/&gt;
 *         &lt;element name="BasisDeterTax" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secRemCovered",
    "amtIncChrgIt",
    "taxLiablIt",
    "basisDeterTax"
})
@XmlRootElement(name = "ItActDetails")
public class ItActDetails {

    @XmlElement(name = "SecRemCovered")
    protected String secRemCovered;
    @XmlElement(name = "AmtIncChrgIt")
    protected BigDecimal amtIncChrgIt;
    @XmlElement(name = "TaxLiablIt")
    protected BigDecimal taxLiablIt;
    @XmlElement(name = "BasisDeterTax")
    protected String basisDeterTax;

    /**
     * Gets the value of the secRemCovered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecRemCovered() {
        return secRemCovered;
    }

    /**
     * Sets the value of the secRemCovered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecRemCovered(String value) {
        this.secRemCovered = value;
    }

    /**
     * Gets the value of the amtIncChrgIt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmtIncChrgIt() {
        return amtIncChrgIt;
    }

    /**
     * Sets the value of the amtIncChrgIt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmtIncChrgIt(BigDecimal value) {
        this.amtIncChrgIt = value;
    }

    /**
     * Gets the value of the taxLiablIt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxLiablIt() {
        return taxLiablIt;
    }

    /**
     * Sets the value of the taxLiablIt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxLiablIt(BigDecimal value) {
        this.taxLiablIt = value;
    }

    /**
     * Gets the value of the basisDeterTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasisDeterTax() {
        return basisDeterTax;
    }

    /**
     * Sets the value of the basisDeterTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasisDeterTax(String value) {
        this.basisDeterTax = value;
    }

}
