//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://incometaxindiaefiling.gov.in/FORM15CAB", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,xmlns = {
        @XmlNs(prefix="xsi", namespaceURI="http://www.w3.org/2001/XMLSchema-instance"),
        @XmlNs(prefix="Form", namespaceURI="http://incometaxindiaefiling.gov.in/common"),
        @XmlNs(prefix="FORM15CA", namespaceURI="http://incometaxindiaefiling.gov.in/FORM15CA"),
        @XmlNs(prefix="FORM15CB", namespaceURI="http://incometaxindiaefiling.gov.in/FORM15CB"),
        @XmlNs(prefix="ns5", namespaceURI="http://incometaxindiaefiling.gov.in/FORM15CAB")
})
package com.ey.in.tds.dividend.fifteen.ca;

import javax.xml.bind.annotation.XmlNs;