//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.ca;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NameRemittee" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}nameType"/&gt;
 *         &lt;element name="PanRemittee" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}panType" minOccurs="0"/&gt;
 *         &lt;element name="StatusRemittee" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="10"/&gt;
 *               &lt;pattern value="[1-4]{1}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RemitteeAddrs" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}addressType"/&gt;
 *         &lt;element name="EmailRemittee" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}emailType" minOccurs="0"/&gt;
 *         &lt;element name="PhoneRemittee" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{10,12}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CountryRemMade" type="{http://incometaxindiaefiling.gov.in/common}countryType" minOccurs="0"/&gt;
 *         &lt;element name="CountryRemMadeDesc" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyString"&gt;
 *               &lt;maxLength value="125"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PrincPlcBusRemtee" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="75"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameRemittee",
    "panRemittee",
    "statusRemittee",
    "remitteeAddrs",
    "emailRemittee",
    "phoneRemittee",
    "countryRemMade",
    "countryRemMadeDesc",
    "princPlcBusRemtee"
})
@XmlRootElement(name = "RemitteeDetls")
public class RemitteeDetls {

    @XmlElement(name = "NameRemittee", required = true)
    protected String nameRemittee;
    @XmlElement(name = "PanRemittee")
    protected String panRemittee;
    @XmlElement(name = "StatusRemittee")
    protected String statusRemittee;
    @XmlElement(name = "RemitteeAddrs", required = true)
    protected AddressType remitteeAddrs;
    @XmlElement(name = "EmailRemittee")
    protected String emailRemittee;
    @XmlElement(name = "PhoneRemittee")
    protected String phoneRemittee;
    @XmlElement(name = "CountryRemMade")
    protected String countryRemMade;
    @XmlElement(name = "CountryRemMadeDesc")
    protected String countryRemMadeDesc;
    @XmlElement(name = "PrincPlcBusRemtee")
    protected String princPlcBusRemtee;

    /**
     * Gets the value of the nameRemittee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRemittee() {
        return nameRemittee;
    }

    /**
     * Sets the value of the nameRemittee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRemittee(String value) {
        this.nameRemittee = value;
    }

    /**
     * Gets the value of the panRemittee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPanRemittee() {
        return panRemittee;
    }

    /**
     * Sets the value of the panRemittee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPanRemittee(String value) {
        this.panRemittee = value;
    }

    /**
     * Gets the value of the statusRemittee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusRemittee() {
        return statusRemittee;
    }

    /**
     * Sets the value of the statusRemittee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusRemittee(String value) {
        this.statusRemittee = value;
    }

    /**
     * Gets the value of the remitteeAddrs property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getRemitteeAddrs() {
        return remitteeAddrs;
    }

    /**
     * Sets the value of the remitteeAddrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setRemitteeAddrs(AddressType value) {
        this.remitteeAddrs = value;
    }

    /**
     * Gets the value of the emailRemittee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailRemittee() {
        return emailRemittee;
    }

    /**
     * Sets the value of the emailRemittee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailRemittee(String value) {
        this.emailRemittee = value;
    }

    /**
     * Gets the value of the phoneRemittee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneRemittee() {
        return phoneRemittee;
    }

    /**
     * Sets the value of the phoneRemittee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneRemittee(String value) {
        this.phoneRemittee = value;
    }

    /**
     * Gets the value of the countryRemMade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryRemMade() {
        return countryRemMade;
    }

    /**
     * Sets the value of the countryRemMade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryRemMade(String value) {
        this.countryRemMade = value;
    }

    /**
     * Gets the value of the countryRemMadeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryRemMadeDesc() {
        return countryRemMadeDesc;
    }

    /**
     * Sets the value of the countryRemMadeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryRemMadeDesc(String value) {
        this.countryRemMadeDesc = value;
    }

    /**
     * Gets the value of the princPlcBusRemtee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrincPlcBusRemtee() {
        return princPlcBusRemtee;
    }

    /**
     * Sets the value of the princPlcBusRemtee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrincPlcBusRemtee(String value) {
        this.princPlcBusRemtee = value;
    }

}
