//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.ca;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NameRemitter" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}nameType"/&gt;
 *         &lt;element name="PAN" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}panTypeDefault" minOccurs="0"/&gt;
 *         &lt;element name="Tan" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}tanType" minOccurs="0"/&gt;
 *         &lt;element name="TanAckPartC" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}tanAckType" minOccurs="0"/&gt;
 *         &lt;element name="RemitterAddrs" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}addressType"/&gt;
 *         &lt;element name="EmailRemitter" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}emailType"/&gt;
 *         &lt;element name="PhoneRemitter" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}phoneType"/&gt;
 *         &lt;element name="Status"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="10"/&gt;
 *               &lt;pattern value="[1-4]{1}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IncTaxWard" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="75"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PrincPlcBusRemter" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="75"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ResidentialStatus" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="10"/&gt;
 *               &lt;pattern value="[1-4]{1}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DomesticFlg" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[1-4]{1}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AreaCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AoType" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RangeCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{3}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AoNumber" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[0-9]{2}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameRemitter",
    "pan",
    "tan",
    "tanAckPartC",
    "remitterAddrs",
    "emailRemitter",
    "phoneRemitter",
    "status",
    "incTaxWard",
    "princPlcBusRemter",
    "residentialStatus",
    "domesticFlg",
    "areaCode",
    "aoType",
    "rangeCode",
    "aoNumber"
})
@XmlRootElement(name = "RemitterDetls")
public class RemitterDetls {

    @XmlElement(name = "NameRemitter", required = true)
    protected String nameRemitter;
    @XmlElement(name = "PAN")
    protected String pan;
    @XmlElement(name = "Tan")
    protected String tan;
    @XmlElement(name = "TanAckPartC")
    protected String tanAckPartC;
    @XmlElement(name = "RemitterAddrs", required = true)
    protected AddressType remitterAddrs;
    @XmlElement(name = "EmailRemitter", required = true)
    protected String emailRemitter;
    @XmlElement(name = "PhoneRemitter", required = true)
    protected String phoneRemitter;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "IncTaxWard")
    protected String incTaxWard;
    @XmlElement(name = "PrincPlcBusRemter")
    protected String princPlcBusRemter;
    @XmlElement(name = "ResidentialStatus")
    protected String residentialStatus;
    @XmlElement(name = "DomesticFlg")
    protected String domesticFlg;
    @XmlElement(name = "AreaCode")
    protected String areaCode;
    @XmlElement(name = "AoType")
    protected String aoType;
    @XmlElement(name = "RangeCode")
    protected String rangeCode;
    @XmlElement(name = "AoNumber")
    protected String aoNumber;

    /**
     * Gets the value of the nameRemitter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRemitter() {
        return nameRemitter;
    }

    /**
     * Sets the value of the nameRemitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRemitter(String value) {
        this.nameRemitter = value;
    }

    /**
     * Gets the value of the pan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAN() {
        return pan;
    }

    /**
     * Sets the value of the pan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAN(String value) {
        this.pan = value;
    }

    /**
     * Gets the value of the tan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTan() {
        return tan;
    }

    /**
     * Sets the value of the tan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTan(String value) {
        this.tan = value;
    }

    /**
     * Gets the value of the tanAckPartC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTanAckPartC() {
        return tanAckPartC;
    }

    /**
     * Sets the value of the tanAckPartC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTanAckPartC(String value) {
        this.tanAckPartC = value;
    }

    /**
     * Gets the value of the remitterAddrs property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getRemitterAddrs() {
        return remitterAddrs;
    }

    /**
     * Sets the value of the remitterAddrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setRemitterAddrs(AddressType value) {
        this.remitterAddrs = value;
    }

    /**
     * Gets the value of the emailRemitter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailRemitter() {
        return emailRemitter;
    }

    /**
     * Sets the value of the emailRemitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailRemitter(String value) {
        this.emailRemitter = value;
    }

    /**
     * Gets the value of the phoneRemitter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneRemitter() {
        return phoneRemitter;
    }

    /**
     * Sets the value of the phoneRemitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneRemitter(String value) {
        this.phoneRemitter = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the incTaxWard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncTaxWard() {
        return incTaxWard;
    }

    /**
     * Sets the value of the incTaxWard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncTaxWard(String value) {
        this.incTaxWard = value;
    }

    /**
     * Gets the value of the princPlcBusRemter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrincPlcBusRemter() {
        return princPlcBusRemter;
    }

    /**
     * Sets the value of the princPlcBusRemter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrincPlcBusRemter(String value) {
        this.princPlcBusRemter = value;
    }

    /**
     * Gets the value of the residentialStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidentialStatus() {
        return residentialStatus;
    }

    /**
     * Sets the value of the residentialStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidentialStatus(String value) {
        this.residentialStatus = value;
    }

    /**
     * Gets the value of the domesticFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomesticFlg() {
        return domesticFlg;
    }

    /**
     * Sets the value of the domesticFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomesticFlg(String value) {
        this.domesticFlg = value;
    }

    /**
     * Gets the value of the areaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * Sets the value of the areaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCode(String value) {
        this.areaCode = value;
    }

    /**
     * Gets the value of the aoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAoType() {
        return aoType;
    }

    /**
     * Sets the value of the aoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAoType(String value) {
        this.aoType = value;
    }

    /**
     * Gets the value of the rangeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRangeCode() {
        return rangeCode;
    }

    /**
     * Sets the value of the rangeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRangeCode(String value) {
        this.rangeCode = value;
    }

    /**
     * Gets the value of the aoNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAoNumber() {
        return aoNumber;
    }

    /**
     * Sets the value of the aoNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAoNumber(String value) {
        this.aoNumber = value;
    }

}
