//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.ca;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AmtPayForgnTds" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}positiveDecimalAmt"/&gt;
 *         &lt;element name="AmtPayIndianTds" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}positiveDecimalAmt"/&gt;
 *         &lt;element name="RateTdsSecbFlg" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="1|2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RateTdsSecB" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}percentage" minOccurs="0"/&gt;
 *         &lt;element name="ActlAmtTdsForgn" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}positiveDecimalAmt" minOccurs="0"/&gt;
 *         &lt;element name="DednDateTds" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "amtPayForgnTds",
    "amtPayIndianTds",
    "rateTdsSecbFlg",
    "rateTdsSecB",
    "actlAmtTdsForgn",
    "dednDateTds"
})
@XmlRootElement(name = "TDSDetails")
public class TDSDetails {

    @XmlElement(name = "AmtPayForgnTds", required = true)
    protected BigDecimal amtPayForgnTds;
    @XmlElement(name = "AmtPayIndianTds", required = true)
    protected BigDecimal amtPayIndianTds;
    @XmlElement(name = "RateTdsSecbFlg")
    protected String rateTdsSecbFlg;
    @XmlElement(name = "RateTdsSecB")
    protected BigDecimal rateTdsSecB;
    @XmlElement(name = "ActlAmtTdsForgn")
    protected BigDecimal actlAmtTdsForgn;
    @XmlElement(name = "DednDateTds")
    protected XMLGregorianCalendar dednDateTds;

    /**
     * Gets the value of the amtPayForgnTds property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmtPayForgnTds() {
        return amtPayForgnTds;
    }

    /**
     * Sets the value of the amtPayForgnTds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmtPayForgnTds(BigDecimal value) {
        this.amtPayForgnTds = value;
    }

    /**
     * Gets the value of the amtPayIndianTds property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmtPayIndianTds() {
        return amtPayIndianTds;
    }

    /**
     * Sets the value of the amtPayIndianTds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmtPayIndianTds(BigDecimal value) {
        this.amtPayIndianTds = value;
    }

    /**
     * Gets the value of the rateTdsSecbFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateTdsSecbFlg() {
        return rateTdsSecbFlg;
    }

    /**
     * Sets the value of the rateTdsSecbFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateTdsSecbFlg(String value) {
        this.rateTdsSecbFlg = value;
    }

    /**
     * Gets the value of the rateTdsSecB property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateTdsSecB() {
        return rateTdsSecB;
    }

    /**
     * Sets the value of the rateTdsSecB property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateTdsSecB(BigDecimal value) {
        this.rateTdsSecB = value;
    }

    /**
     * Gets the value of the actlAmtTdsForgn property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActlAmtTdsForgn() {
        return actlAmtTdsForgn;
    }

    /**
     * Sets the value of the actlAmtTdsForgn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActlAmtTdsForgn(BigDecimal value) {
        this.actlAmtTdsForgn = value;
    }

    /**
     * Gets the value of the dednDateTds property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDednDateTds() {
        return dednDateTds;
    }

    /**
     * Sets the value of the dednDateTds property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDednDateTds(XMLGregorianCalendar value) {
        this.dednDateTds = value;
    }

}
