//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.cb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcctntDetls complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcctntDetls"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NameAcctnt"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NameFirmAcctnt"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AcctntAddrs" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}addressType"/&gt;
 *         &lt;element name="MembershipNumber"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="6"/&gt;
 *               &lt;maxLength value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RegNoAcctnt" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="8"/&gt;
 *               &lt;maxLength value="8"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcctntDetls", propOrder = {
    "nameAcctnt",
    "nameFirmAcctnt",
    "acctntAddrs",
    "membershipNumber",
    "regNoAcctnt"
})
public class AcctntDetls {

    @XmlElement(name = "NameAcctnt", required = true)
    protected String nameAcctnt;
    @XmlElement(name = "NameFirmAcctnt", required = true)
    protected String nameFirmAcctnt;
    @XmlElement(name = "AcctntAddrs", required = true)
    protected AddressType acctntAddrs;
    @XmlElement(name = "MembershipNumber", required = true)
    protected String membershipNumber;
    @XmlElement(name = "RegNoAcctnt")
    protected String regNoAcctnt;

    /**
     * Gets the value of the nameAcctnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameAcctnt() {
        return nameAcctnt;
    }

    /**
     * Sets the value of the nameAcctnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameAcctnt(String value) {
        this.nameAcctnt = value;
    }

    /**
     * Gets the value of the nameFirmAcctnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameFirmAcctnt() {
        return nameFirmAcctnt;
    }

    /**
     * Sets the value of the nameFirmAcctnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameFirmAcctnt(String value) {
        this.nameFirmAcctnt = value;
    }

    /**
     * Gets the value of the acctntAddrs property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAcctntAddrs() {
        return acctntAddrs;
    }

    /**
     * Sets the value of the acctntAddrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAcctntAddrs(AddressType value) {
        this.acctntAddrs = value;
    }

    /**
     * Gets the value of the membershipNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMembershipNumber() {
        return membershipNumber;
    }

    /**
     * Sets the value of the membershipNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMembershipNumber(String value) {
        this.membershipNumber = value;
    }

    /**
     * Gets the value of the regNoAcctnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegNoAcctnt() {
        return regNoAcctnt;
    }

    /**
     * Sets the value of the regNoAcctnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegNoAcctnt(String value) {
        this.regNoAcctnt = value;
    }

}
