//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.cb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PremisesBuildingVillage" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/common}nonEmptyString"&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TownCityDistrict"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/common}nonEmptyString"&gt;
 *               &lt;maxLength value="50"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FlatDoorBuilding"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/common}nonEmptyString"&gt;
 *               &lt;maxLength value="50"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AreaLocality"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/common}nonEmptyString"&gt;
 *               &lt;maxLength value="50"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Pincode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/common}nonEmptyString"&gt;
 *               &lt;pattern value="[0-9]{6}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ZipCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="8"/&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{http://incometaxindiaefiling.gov.in/common}State"/&gt;
 *         &lt;element name="RoadStreet" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/common}nonEmptyString"&gt;
 *               &lt;maxLength value="50"/&gt;
 *               &lt;minLength value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Country" type="{http://incometaxindiaefiling.gov.in/common}countryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressType", propOrder = {
    "premisesBuildingVillage",
    "townCityDistrict",
    "flatDoorBuilding",
    "areaLocality",
    "pincode",
    "zipCode",
    "state",
    "roadStreet",
    "country"
})
public class AddressType {

    @XmlElement(name = "PremisesBuildingVillage")
    protected String premisesBuildingVillage;
    @XmlElement(name = "TownCityDistrict", required = true)
    protected String townCityDistrict;
    @XmlElement(name = "FlatDoorBuilding", required = true)
    protected String flatDoorBuilding;
    @XmlElement(name = "AreaLocality", required = true)
    protected String areaLocality;
    @XmlElement(name = "Pincode")
    protected String pincode;
    @XmlElement(name = "ZipCode")
    protected String zipCode;
    @XmlElement(name = "State", namespace = "http://incometaxindiaefiling.gov.in/common", required = true)
    protected String state;
    @XmlElement(name = "RoadStreet")
    protected String roadStreet;
    @XmlElement(name = "Country", required = true)
    protected String country;

    /**
     * Gets the value of the premisesBuildingVillage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPremisesBuildingVillage() {
        return premisesBuildingVillage;
    }

    /**
     * Sets the value of the premisesBuildingVillage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPremisesBuildingVillage(String value) {
        this.premisesBuildingVillage = value;
    }

    /**
     * Gets the value of the townCityDistrict property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTownCityDistrict() {
        return townCityDistrict;
    }

    /**
     * Sets the value of the townCityDistrict property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTownCityDistrict(String value) {
        this.townCityDistrict = value;
    }

    /**
     * Gets the value of the flatDoorBuilding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlatDoorBuilding() {
        return flatDoorBuilding;
    }

    /**
     * Sets the value of the flatDoorBuilding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlatDoorBuilding(String value) {
        this.flatDoorBuilding = value;
    }

    /**
     * Gets the value of the areaLocality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaLocality() {
        return areaLocality;
    }

    /**
     * Sets the value of the areaLocality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaLocality(String value) {
        this.areaLocality = value;
    }

    /**
     * Gets the value of the pincode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPincode() {
        return pincode;
    }

    /**
     * Sets the value of the pincode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPincode(String value) {
        this.pincode = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the roadStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadStreet() {
        return roadStreet;
    }

    /**
     * Sets the value of the roadStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadStreet(String value) {
        this.roadStreet = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

}
