//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.cb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TaxResidCert"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="Y|N"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RelevantDtaa" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="30"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RelevantArtDtaa" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TaxIncDtaa" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}positiveDecimalAmt" minOccurs="0"/&gt;
 *         &lt;element name="TaxLiablDtaa" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}positiveDecimalAmt" minOccurs="0"/&gt;
 *         &lt;element name="RemForRoyFlg"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="Y|N"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ArtDtaa" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RateTdsADtaa" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}percentage" minOccurs="0"/&gt;
 *         &lt;element name="RemAcctBusIncFlg"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="Y|N"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IncLiabIndiaFlg" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="Y|N|-1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ArrAtRateDedTax" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ReasonofReleventArtDtaa" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RemOnCapGainFlg"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="Y|N"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="AmtLongTrm" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}positiveDecimalAmt" minOccurs="0"/&gt;
 *         &lt;element name="AmtShortTrm" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}positiveDecimalAmt" minOccurs="0"/&gt;
 *         &lt;element name="BasisTaxIncDtaa" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OtherRemDtaa"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="Y|N"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NatureRemDtaa" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TaxIndDtaaFlg" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="Y|N"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RateTdsDDtaa" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RelArtDetlDDtaa" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://incometaxindiaefiling.gov.in/FORM15CAB}nonEmptyStringOnlyCaps"&gt;
 *               &lt;maxLength value="125"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "taxResidCert",
    "relevantDtaa",
    "relevantArtDtaa",
    "taxIncDtaa",
    "taxLiablDtaa",
    "remForRoyFlg",
    "artDtaa",
    "rateTdsADtaa",
    "remAcctBusIncFlg",
    "incLiabIndiaFlg",
    "arrAtRateDedTax",
    "reasonofReleventArtDtaa",
    "remOnCapGainFlg",
    "amtLongTrm",
    "amtShortTrm",
    "basisTaxIncDtaa",
    "otherRemDtaa",
    "natureRemDtaa",
    "taxIndDtaaFlg",
    "rateTdsDDtaa",
    "relArtDetlDDtaa"
})
@XmlRootElement(name = "DTAADetails")
public class DTAADetails {

    @XmlElement(name = "TaxResidCert", required = true)
    protected String taxResidCert;
    @XmlElement(name = "RelevantDtaa")
    protected String relevantDtaa;
    @XmlElement(name = "RelevantArtDtaa")
    protected String relevantArtDtaa;
    @XmlElement(name = "TaxIncDtaa")
    protected BigDecimal taxIncDtaa;
    @XmlElement(name = "TaxLiablDtaa")
    protected BigDecimal taxLiablDtaa;
    @XmlElement(name = "RemForRoyFlg", required = true)
    protected String remForRoyFlg;
    @XmlElement(name = "ArtDtaa")
    protected String artDtaa;
    @XmlElement(name = "RateTdsADtaa")
    protected BigDecimal rateTdsADtaa;
    @XmlElement(name = "RemAcctBusIncFlg", required = true)
    protected String remAcctBusIncFlg;
    @XmlElement(name = "IncLiabIndiaFlg")
    protected String incLiabIndiaFlg;
    @XmlElement(name = "ArrAtRateDedTax")
    protected String arrAtRateDedTax;
    @XmlElement(name = "ReasonofReleventArtDtaa")
    protected String reasonofReleventArtDtaa;
    @XmlElement(name = "RemOnCapGainFlg", required = true)
    protected String remOnCapGainFlg;
    @XmlElement(name = "AmtLongTrm")
    protected BigDecimal amtLongTrm;
    @XmlElement(name = "AmtShortTrm")
    protected BigDecimal amtShortTrm;
    @XmlElement(name = "BasisTaxIncDtaa")
    protected String basisTaxIncDtaa;
    @XmlElement(name = "OtherRemDtaa", required = true)
    protected String otherRemDtaa;
    @XmlElement(name = "NatureRemDtaa")
    protected String natureRemDtaa;
    @XmlElement(name = "TaxIndDtaaFlg")
    protected String taxIndDtaaFlg;
    @XmlElement(name = "RateTdsDDtaa")
    protected String rateTdsDDtaa;
    @XmlElement(name = "RelArtDetlDDtaa")
    protected String relArtDetlDDtaa;

    /**
     * Gets the value of the taxResidCert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxResidCert() {
        return taxResidCert;
    }

    /**
     * Sets the value of the taxResidCert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxResidCert(String value) {
        this.taxResidCert = value;
    }

    /**
     * Gets the value of the relevantDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelevantDtaa() {
        return relevantDtaa;
    }

    /**
     * Sets the value of the relevantDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelevantDtaa(String value) {
        this.relevantDtaa = value;
    }

    /**
     * Gets the value of the relevantArtDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelevantArtDtaa() {
        return relevantArtDtaa;
    }

    /**
     * Sets the value of the relevantArtDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelevantArtDtaa(String value) {
        this.relevantArtDtaa = value;
    }

    /**
     * Gets the value of the taxIncDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxIncDtaa() {
        return taxIncDtaa;
    }

    /**
     * Sets the value of the taxIncDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxIncDtaa(BigDecimal value) {
        this.taxIncDtaa = value;
    }

    /**
     * Gets the value of the taxLiablDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxLiablDtaa() {
        return taxLiablDtaa;
    }

    /**
     * Sets the value of the taxLiablDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxLiablDtaa(BigDecimal value) {
        this.taxLiablDtaa = value;
    }

    /**
     * Gets the value of the remForRoyFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemForRoyFlg() {
        return remForRoyFlg;
    }

    /**
     * Sets the value of the remForRoyFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemForRoyFlg(String value) {
        this.remForRoyFlg = value;
    }

    /**
     * Gets the value of the artDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtDtaa() {
        return artDtaa;
    }

    /**
     * Sets the value of the artDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtDtaa(String value) {
        this.artDtaa = value;
    }

    /**
     * Gets the value of the rateTdsADtaa property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRateTdsADtaa() {
        return rateTdsADtaa;
    }

    /**
     * Sets the value of the rateTdsADtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRateTdsADtaa(BigDecimal value) {
        this.rateTdsADtaa = value;
    }

    /**
     * Gets the value of the remAcctBusIncFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemAcctBusIncFlg() {
        return remAcctBusIncFlg;
    }

    /**
     * Sets the value of the remAcctBusIncFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemAcctBusIncFlg(String value) {
        this.remAcctBusIncFlg = value;
    }

    /**
     * Gets the value of the incLiabIndiaFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncLiabIndiaFlg() {
        return incLiabIndiaFlg;
    }

    /**
     * Sets the value of the incLiabIndiaFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncLiabIndiaFlg(String value) {
        this.incLiabIndiaFlg = value;
    }

    /**
     * Gets the value of the arrAtRateDedTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrAtRateDedTax() {
        return arrAtRateDedTax;
    }

    /**
     * Sets the value of the arrAtRateDedTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrAtRateDedTax(String value) {
        this.arrAtRateDedTax = value;
    }

    /**
     * Gets the value of the reasonofReleventArtDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonofReleventArtDtaa() {
        return reasonofReleventArtDtaa;
    }

    /**
     * Sets the value of the reasonofReleventArtDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonofReleventArtDtaa(String value) {
        this.reasonofReleventArtDtaa = value;
    }

    /**
     * Gets the value of the remOnCapGainFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemOnCapGainFlg() {
        return remOnCapGainFlg;
    }

    /**
     * Sets the value of the remOnCapGainFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemOnCapGainFlg(String value) {
        this.remOnCapGainFlg = value;
    }

    /**
     * Gets the value of the amtLongTrm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmtLongTrm() {
        return amtLongTrm;
    }

    /**
     * Sets the value of the amtLongTrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmtLongTrm(BigDecimal value) {
        this.amtLongTrm = value;
    }

    /**
     * Gets the value of the amtShortTrm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmtShortTrm() {
        return amtShortTrm;
    }

    /**
     * Sets the value of the amtShortTrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmtShortTrm(BigDecimal value) {
        this.amtShortTrm = value;
    }

    /**
     * Gets the value of the basisTaxIncDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasisTaxIncDtaa() {
        return basisTaxIncDtaa;
    }

    /**
     * Sets the value of the basisTaxIncDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasisTaxIncDtaa(String value) {
        this.basisTaxIncDtaa = value;
    }

    /**
     * Gets the value of the otherRemDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherRemDtaa() {
        return otherRemDtaa;
    }

    /**
     * Sets the value of the otherRemDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherRemDtaa(String value) {
        this.otherRemDtaa = value;
    }

    /**
     * Gets the value of the natureRemDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNatureRemDtaa() {
        return natureRemDtaa;
    }

    /**
     * Sets the value of the natureRemDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNatureRemDtaa(String value) {
        this.natureRemDtaa = value;
    }

    /**
     * Gets the value of the taxIndDtaaFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxIndDtaaFlg() {
        return taxIndDtaaFlg;
    }

    /**
     * Sets the value of the taxIndDtaaFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxIndDtaaFlg(String value) {
        this.taxIndDtaaFlg = value;
    }

    /**
     * Gets the value of the rateTdsDDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateTdsDDtaa() {
        return rateTdsDDtaa;
    }

    /**
     * Sets the value of the rateTdsDDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateTdsDDtaa(String value) {
        this.rateTdsDDtaa = value;
    }

    /**
     * Gets the value of the relArtDetlDDtaa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelArtDetlDDtaa() {
        return relArtDetlDDtaa;
    }

    /**
     * Sets the value of the relArtDetlDDtaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelArtDetlDDtaa(String value) {
        this.relArtDetlDDtaa = value;
    }

}
