//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.cb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ey.in.tds.dividend.fifteen.cb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AcctntDetls_QNAME = new QName("http://incometaxindiaefiling.gov.in/FORM15CAB", "AcctntDetls");
    private final static QName _State_QNAME = new QName("http://incometaxindiaefiling.gov.in/common", "State");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ey.in.tds.dividend.fifteen.cb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FORM15CB }
     * 
     */
    public FORM15CB createFORM15CB() {
        return new FORM15CB();
    }

    /**
     * Create an instance of {@link CreationInfo }
     * 
     */
    public CreationInfo createCreationInfo() {
        return new CreationInfo();
    }

    /**
     * Create an instance of {@link FormDetails }
     * 
     */
    public FormDetails createFormDetails() {
        return new FormDetails();
    }

    /**
     * Create an instance of {@link RemitterDetails }
     * 
     */
    public RemitterDetails createRemitterDetails() {
        return new RemitterDetails();
    }

    /**
     * Create an instance of {@link RemitteeDetls }
     * 
     */
    public RemitteeDetls createRemitteeDetls() {
        return new RemitteeDetls();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link RemittanceDetails }
     * 
     */
    public RemittanceDetails createRemittanceDetails() {
        return new RemittanceDetails();
    }

    /**
     * Create an instance of {@link ItActDetails }
     * 
     */
    public ItActDetails createItActDetails() {
        return new ItActDetails();
    }

    /**
     * Create an instance of {@link DTAADetails }
     * 
     */
    public DTAADetails createDTAADetails() {
        return new DTAADetails();
    }

    /**
     * Create an instance of {@link TDSDetails }
     * 
     */
    public TDSDetails createTDSDetails() {
        return new TDSDetails();
    }

    /**
     * Create an instance of {@link AcctntDetls }
     * 
     */
    public AcctntDetls createAcctntDetls() {
        return new AcctntDetls();
    }

    /**
     * Create an instance of {@link Amountoftds }
     * 
     */
    public Amountoftds createAmountoftds() {
        return new Amountoftds();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcctntDetls }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://incometaxindiaefiling.gov.in/FORM15CAB", name = "AcctntDetls")
    public JAXBElement<AcctntDetls> createAcctntDetls(AcctntDetls value) {
        return new JAXBElement<AcctntDetls>(_AcctntDetls_QNAME, AcctntDetls.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://incometaxindiaefiling.gov.in/common", name = "State")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

}
