//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.cb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IorWe"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="01|02"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RemitterHonorific"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="01|02|03"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NameRemitter" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}nameType"/&gt;
 *         &lt;element name="PAN" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}panTanType"/&gt;
 *         &lt;element name="BeneficiaryHonorific"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="01|02|03"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iorWe",
    "remitterHonorific",
    "nameRemitter",
    "pan",
    "beneficiaryHonorific"
})
@XmlRootElement(name = "RemitterDetails")
public class RemitterDetails {

    @XmlElement(name = "IorWe", required = true)
    protected String iorWe;
    @XmlElement(name = "RemitterHonorific", required = true)
    protected String remitterHonorific;
    @XmlElement(name = "NameRemitter", required = true)
    protected String nameRemitter;
    @XmlElement(name = "PAN", required = true)
    protected String pan;
    @XmlElement(name = "BeneficiaryHonorific", required = true)
    protected String beneficiaryHonorific;

    /**
     * Gets the value of the iorWe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIorWe() {
        return iorWe;
    }

    /**
     * Sets the value of the iorWe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIorWe(String value) {
        this.iorWe = value;
    }

    /**
     * Gets the value of the remitterHonorific property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemitterHonorific() {
        return remitterHonorific;
    }

    /**
     * Sets the value of the remitterHonorific property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemitterHonorific(String value) {
        this.remitterHonorific = value;
    }

    /**
     * Gets the value of the nameRemitter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRemitter() {
        return nameRemitter;
    }

    /**
     * Sets the value of the nameRemitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRemitter(String value) {
        this.nameRemitter = value;
    }

    /**
     * Gets the value of the pan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAN() {
        return pan;
    }

    /**
     * Sets the value of the pan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAN(String value) {
        this.pan = value;
    }

    /**
     * Gets the value of the beneficiaryHonorific property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneficiaryHonorific() {
        return beneficiaryHonorific;
    }

    /**
     * Sets the value of the beneficiaryHonorific property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneficiaryHonorific(String value) {
        this.beneficiaryHonorific = value;
    }

}
