//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.20 at 07:06:56 PM IST 
//


package com.ey.in.tds.dividend.fifteen.cb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NameRemittee" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}nameType"/&gt;
 *         &lt;element name="RemitteeAddrs" type="{http://incometaxindiaefiling.gov.in/FORM15CAB}addressType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameRemittee",
    "remitteeAddrs"
})
@XmlRootElement(name = "RemitteeDetls")
public class RemitteeDetls {

    @XmlElement(name = "NameRemittee", required = true)
    protected String nameRemittee;
    @XmlElement(name = "RemitteeAddrs", required = true)
    protected AddressType remitteeAddrs;

    /**
     * Gets the value of the nameRemittee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRemittee() {
        return nameRemittee;
    }

    /**
     * Sets the value of the nameRemittee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRemittee(String value) {
        this.nameRemittee = value;
    }

    /**
     * Gets the value of the remitteeAddrs property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getRemitteeAddrs() {
        return remitteeAddrs;
    }

    /**
     * Sets the value of the remitteeAddrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setRemitteeAddrs(AddressType value) {
        this.remitteeAddrs = value;
    }

}
