# Port configuration
server:
  port: 8001
  

# View resolver configuration
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

#profile configuration for different environment
  profiles:
  - pe