FROM centos:centos7

MAINTAINER TFO

# Install prepare infrastructure
RUN yum -y update && \
    yum -y install wget && \
    yum -y install tar \
    yum -y install unzip


# Chrome and Selenium.

ADD /src/main/resources/google-chrome.repo /etc/yum.repos.d/google-chrome.repo 

RUN yum install -y https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-84.0.4147.135-1.x86_64.rpm

# Install ChromeDriver.
RUN wget -N https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip -P ~/
RUN unzip ~/chromedriver_linux64.zip -d ~/
RUN rm ~/chromedriver_linux64.zip
RUN mv -f ~/chromedriver /usr/local/bin/chromedriver
RUN chown root:root /usr/local/bin/chromedriver
RUN chmod 0755 /usr/local/bin/chromedriver



RUN yum install -y \
       java-1.8.0-openjdk \
       java-1.8.0-openjdk-devel

# Prepare environment
ENV JAVA_HOME /etc/alternatives/jre
ENV CATALINA_HOME /opt/tomcat
ENV PATH $PATH:$JAVA_HOME/bin
ENV TZ Asia/Kolkata

WORKDIR /opt/tomcat/
ADD /src/main/resources/xsd /opt/tomcat/xsd


ADD /target/tds-returns-3.2.jar  /opt/tomcat/tds-returns-3.2.jar

EXPOSE 80

USER root
CMD java $JAVA_OPTS -Djava.awt.headless=true -jar -Dserver.port=80 /opt/tomcat/tds-returns-3.2.jar