FROM centos:centos7

MAINTAINER TFO

# Install prepare infrastructure
RUN yum -y update && \
    yum -y install wget && \
    yum -y install tar

# Prepare environment
RUN yum install -y \
       java-1.8.0-openjdk \
       java-1.8.0-openjdk-devel

# Prepare environment
ENV JAVA_HOME /etc/alternatives/jre
ENV CATALINA_HOME /opt/tomcat
ENV PATH $PATH:$JAVA_HOME/bin
ENV TZ Asia/Kolkata

WORKDIR /opt/tomcat/

ADD /target/tds-masters-3.2.jar  /opt/tomcat/tds-masters-3.2.jar



EXPOSE 80

USER root
CMD java -jar -Dserver.port=80 /opt/tomcat/tds-masters-3.2.jar